#### Download image Alpine linux from Docker.Hub ####
FROM alpine

#### Install Mysql-Server && Apache web-server #### 
RUN apk add mysql-server && \
  
  apk add apache2 && \
  
#### Start Apache web-server ####
CMD ls -la
