version: '3'

networks:
  monitoring:
    driver: bridge

services:
   
  prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
        volumes:
           - ./config:/etc/prometheus
        command:
           - --config.file=/etc/prometheus/prometheus.yml
           - --storage.tsdb.path=/prometheus
           - --web.console.libraries=/etc/prometheus/console_libraries
           - --web.console.templates=/etc/prometheus/consoles
           - --storage.tsdb.retention.time=200h
           - --web.enable-lifecycle
        restart: always
        networks:
           - monitoring
        expose:
           - 9090
        ports:
           - 9090:9090

  node_exporter:
        image: prom/node-exporter
        container_name: node_exporter
        depends_on:
           - prometheus
        restart: always
        networks:
           - monitoring
        expose: 
           - 9100

  cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        depends_on:
           - prometheus
        restart: always
        networks:
           - monitoring
        expose:
           - 8080
