version: "3.4"

networks:
  smp-net:
    external: true 

services:
  
  grafana:
    image: grafana/grafana:7.2.2
    container_name: grafana
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana/plugins:/etc/grafana/provisioning/plugins
    ports:
      - "3000:3000"
    networks:
      - smp-net

# Docker Logs
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    volumes:
      - ./loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - smp-net

# Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - smp-net
 
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - smp-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - smp-net


# Metrics SQL Server
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    volumes:
      - "./influxdb:/etc/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_USER_PASSWORD=admin"
      - "INFLUXDB_DB=influx"
      - "INFLUXDB_USER=admin"
      - "INFLUXDB_USER_PASSWORD=admin"
    ports:
      - 8086:8086
    networks:
      - smp-net

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
    networks:
      - smp-net



